import os
import typer
from pathlib import Path

app = typer.Typer()

def generate_structure_from_output(txt_file: Path, base_path: Path):
    """
    Generate the folder and file structure from the output of the source code converter.
    Creates everything under a folder named after the `.txt` file.
    
    Args:
        txt_file (Path): Path to the text file generated by the source code converter.
        base_path (Path): Base path where the structure will be created.
    """
    try:
        # Create a new directory named after the txt file (without extension)
        output_dir = base_path / txt_file.stem
        output_dir.mkdir(parents=True, exist_ok=True)
        print(f"Creating structure in: {output_dir}")

        with open(txt_file, 'r') as file:
            current_file_path = None
            for line in file:
                line = line.strip()
                if line.startswith("### SOURCE FILE:"):
                    # Extract the file path from the line
                    current_file_path = line.split("### SOURCE FILE:")[1].strip()
                    # Determine the full path under the new output directory
                    full_path = output_dir / current_file_path
                    # Create the parent directories
                    full_path.parent.mkdir(parents=True, exist_ok=True)
                    # Create the file itself (empty for now)
                    full_path.touch()
                    print(f"Created file: {full_path}")
                elif current_file_path and line:
                    # Write the content to the file (append to existing file)
                    with open(output_dir / current_file_path, 'a', encoding='utf-8') as content_file:
                        content_file.write(line + '\n')
    except Exception as e:
        print(f"Error: {e}")

@app.command()
def recreate_structure(
    txt_file: Path = typer.Argument(..., help="Path to the output text file from the converter"),
    base_path: Path = typer.Option(Path("."), help="Base path where the structure will be created")
):
    """
    Recreate the folder and file structure from the output text file generated by the source code converter.
    Everything is recreated under a folder named after the text file (without extension).
    """
    generate_structure_from_output(txt_file, base_path)

if __name__ == "__main__":
    app()
